///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

#define TRACK_COUNT 5
#define RANDOM_TRACK_COUNT 1
#define MODERN_CUP_COUNT 9
#define RETRO_CUP_COUNT 1
#define VARIETY_CUP_COUNT 1
#define BATTLE_CUP_COUNT 1
#define VS_CUP_COUNT ((MODERN_CUP_COUNT > RETRO_CUP_COUNT) \
    ? ((MODERN_CUP_COUNT > VARIETY_CUP_COUNT) ? MODERN_CUP_COUNT : VARIETY_CUP_COUNT) \
    : ((RETRO_CUP_COUNT > VARIETY_CUP_COUNT) ? RETRO_CUP_COUNT : VARIETY_CUP_COUNT))
