///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

#define TRACK_COUNT 5
#define ARENA_COUNT 2
#define RANDOM_TRACK_COUNT 1
#define RANDOM_ARENA_COUNT 1
#define MODERN_CUP_COUNT 9
#define RETRO_CUP_COUNT 1
#define VARIETY_CUP_COUNT 1
#define BATTLE_CUP_COUNT 1
