///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

#define TRACK_COUNT 5
#define CUP_COUNT 9
#define ARENA_COUNT 1
#define BATTLE_CUP_COUNT 1
#define RANDOM_TRACK_COUNT 1
#define RANDOM_ARENA_COUNT 1
