#include "cupsystem/CupData.h"

///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

const CupFile::Track CupFile::tracks[] = {
    {4, 2, 0x2391, 0, 0, 0, 0},
    {5, 7, 0x2392, 0, 0, 0, 0},
    {3, 3, 0x2393, 0, 0, 0, 0},
    {10, 4, 0x2394, 0, 0, 0, 0},
    {28, 19, 0x2395, 0, 0, 0, 0},
};

const u16 rnd_001_trx[] = {0, 1};
const u8 rnd_001_chn[] = {128, 128};

const CupFile::RandomTrack CupFile::randomTracks[] = {
    {ARRAY_SIZE(rnd_001_trx), 0x2390, rnd_001_trx, rnd_001_chn},
};

const CupFile::Cup cupsModern[] = {
    {0x23C7, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23C8, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23C9, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CA, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CB, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CC, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CD, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CE, {2, 3, IS_RANDOM | 0, 4, 0}},
    {0x23CF, {2, 3, IS_RANDOM | 0, 4, 0}},
};

const CupFile::Cup cupsRetro[] = {
    {0x23C7, {2, 3, IS_RANDOM | 0, 4, 0}},
};

const CupFile::Cup cupsVariety[] = {
    {0x23C7, {2, 3, IS_RANDOM | 0, 4, 0}},
};

const CupFile::Cup cupsBattle[] = {
    {0x23C7, {0, 1, IS_RANDOM | 0, 1, 1}},
};

const CupFile::CupHolder CupFile::cupHolder[] = {
    {0, ARRAY_SIZE(cupsModern), cupsModern, CUP_ICON_DIR_VS_MODERN "/%d.tpl"},
    {0, ARRAY_SIZE(cupsRetro), cupsRetro, CUP_ICON_DIR_VS_RETRO "/%d.tpl"},
    {0, ARRAY_SIZE(cupsVariety), cupsVariety, CUP_ICON_DIR_VS_VARIETY "/%d.tpl"},
    {0, ARRAY_SIZE(cupsBattle), cupsBattle, CUP_ICON_DIR_BT "/%d.tpl"},
};
