#include "cupsystem/CupData.h"

///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

const CupFile::Track tracks[TRACK_COUNT] = {
    {0, 0, 0, 0, 0, 4, 0x7B},
    {0, 0, 0, 0, 0, 5, 0x7F},
    {0, 0, 0, 0, 0, 3, 0x8B},
    {0, 0, 0, 0, 0, 10, 0x8D},
    {0, 0, 0, 0, 0, 28, 0xA3},
};

const u16 rnd_001_trx[] = {0, 1};
const u8 rnd_001_chn[] = {128, 128};

const CupFile::RandomTrack randomTracks[RANDOM_TRACK_COUNT] = {
    {2, 0x2390, rnd_001_trx, rnd_001_chn},
};

const CupFile::Cup cups[CUP_COUNT] = {
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
    {0x2489, {2, 3, 0x8000, 4, 0}},
};
