#include "cupsystem/CupData.h"

///////////////////////////////////////////////////////
// This file is autogenerated. DO NOT EDIT MANUALLY. //
///////////////////////////////////////////////////////

const CupFile::Track CupFile::tracks[TRACK_COUNT] = {
    {0, 0, 0, 0, 0, 4, 0x7B},
    {0, 0, 0, 0, 0, 5, 0x7F},
    {0, 0, 0, 0, 0, 3, 0x8B},
    {0, 0, 0, 0, 0, 10, 0x8D},
    {0, 0, 0, 0, 0, 28, 0xA3},
};

const u16 rnd_001_trx[] = {0, 1};
const u8 rnd_001_chn[] = {128, 128};

const CupFile::RandomTrack CupFile::randomTracks[RANDOM_TRACK_COUNT] = {
    {2, 0x2390, rnd_001_trx, rnd_001_chn},
};

const CupFile::Cup CupFile::cups[CUP_COUNT] = {
    {0x23C7, {2, 3, 0x8000, 4, -1}},
    {0x23C8, {2, 3, 0x8000, 4, -1}},
    {0x23C9, {2, 3, 0x8000, 4, -1}},
    {0x23CA, {2, 3, 0x8000, 4, -1}},
    {0x23CB, {2, 3, 0x8000, 4, -1}},
    {0x23CC, {2, 3, 0x8000, 4, -1}},
    {0x23CD, {2, 3, 0x8000, 4, -1}},
    {0x23CE, {2, 3, 0x8000, 4, -1}},
    {0x23CF, {2, 3, 0x8000, 4, -1}},
};
